services:
  # Node.js service for admin interface and worker management
  worker-admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./DATA/workers:/app/DATA/workers
      - ./admin/templates:/app/templates
    environment:
      - NODE_ENV=production
      - API_KEY=${API_KEY}
      - KV_SERVICE_URL=http://kv-service:3001
    depends_on:
      - kv-service
    restart: unless-stopped

  # Standalone KV service
  kv-service:
    build:
      context: ./kv-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./DATA/kv:/app/DATA/kv
    environment:
      - NODE_ENV=production
      - API_KEY=${API_KEY}
    restart: unless-stopped

  # Workerd runtime service
  workerd:
    build:
      context: ./workerd-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
      - "8088:8088"
    volumes:
      - ./DATA/workers:/app/DATA/workers
      - ./commons:/app/commons
    environment:
      - NODE_ENV=production
      - API_KEY=${API_KEY}
    depends_on:
      - worker-admin
      - kv-service
    restart: unless-stopped

volumes:
  kv-data:
